coverage_service: coveralls
xcodeproj: ./SampleObjC/MockUIAlertControllerSample.xcodeproj
scheme: MockUIAlertControllerSample
build_directory: ./build
binary_file: ./build/Debug-iphonesimulator/MockUIAlertControllerSample.app/PlugIns/MockUIAlertControllerSampleTests.xctest/MockUIAlertControllerSampleTests
ignore:
  - SampleObjC/*
verbose_mode: true
