coverage_service: coveralls
xcodeproj: ./SampleObjC/MockUIAlertControllerSample.xcodeproj
scheme: MockUIAlertControllerSample
binary_file: /Users/travis/Library/Developer/Xcode/DerivedData/MockUIAlertControllerSample-fzpnwcxasbqkdqfgenrbrufzymgx/Build/Products/Debug-iphonesimulator/MockUIAlertControllerSample.app/PlugIns/MockUIAlertControllerSampleTests.xctest/MockUIAlertControllerSampleTests
ignore:
  - SampleObjC/*
