coverage_service: coveralls
xcodeproj: ./SampleObjC/MockUIAlertControllerSample.xcodeproj
scheme: MockUIAlertControllerSample
build_directory: ./build
binary_file: /Users/jmreid/Library/Developer/Xcode/DerivedData/MockUIAlertControllerSample-guopqxlknwoqrrcpydnkjwhjmorw/Build/Products/Debug-iphonesimulator/MockUIAlertControllerSample.app/PlugIns/MockUIAlertControllerSampleTests.xctest/MockUIAlertControllerSampleTests
ignore:
  - SampleObjC/*
