language: objective-c

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
  - xctool test -project Sample/MockUIAlertControllerSample.xcodeproj -scheme libochamcrest -sdk iphonesimulator8.3 -destination "platform=iOS Simulator,name=iPhone 5,OS=8.3"
  - xctool test -project Sample/MockUIAlertControllerSample.xcodeproj -scheme libochamcrest -sdk iphonesimulator8.3 -destination "platform=iOS Simulator,name=iPhone 5s,OS=8.3"
  - xctool test -project Sample/MockUIAlertControllerSample.xcodeproj -scheme libochamcrest -sdk iphonesimulator8.3 -destination "platform=iOS Simulator,name=iPad Air,OS=8.3"

