language: objective-c
osx_image: xcode11.6

script:
  - set -o pipefail;
  - xcodebuild test -project ObjCSample/ObjCSampleViewControllerPresentationSpy.xcodeproj -scheme ObjCSampleViewControllerPresentationSpy -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 8" | xcpretty
  - xcodebuild test -project SwiftSample/SwiftSampleViewControllerPresentationSpy.xcodeproj -scheme SwiftSampleViewControllerPresentationSpy -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 8" | xcpretty
  - xcodebuild test -project SwiftSample/SwiftSampleViewControllerPresentationSpy.xcodeproj -scheme SwiftSampleViewControllerPresentationSpy -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPad Air" | xcpretty
  - pod spec lint --quick
